### ISSUE TITLE
Google Messages reactions

### ISSUE THREAD

**Issue by R9TRH** [polodarb/GMS-Flags#20]
Hi please add a flag to enable reactions on messages in the recommended tab.

**Comment by HmidouZaka** [comment]
ok I will do it ,can I ask you something

**Comment by polodarb** [comment]
I can't find all the right flags for this at the moment

**Comment by polodarb** [comment]
I found the flags, I’ll post them on Friday along with the app update :)

**Comment by R9TRH** [comment]
Very thanks 🩵🩵
