### ISSUE TITLE
App stuck

### ISSUE THREAD

**Issue by Rafee-M** [polodarb/GMS-Flags#28]
Launching the app right after the install:
![Screenshot_2023-12-21-20-57-32-12_3508d0c822375400d1fdf25e7f935314](https://github.com/polodarb/GMS-Flags/assets/69535896/a09b3483-3f62-4784-940d-cd11215d882a)

Launching the app after closing the app:

![Screenshot_2023-12-21-20-56-10-81_3508d0c822375400d1fdf25e7f935314](https://github.com/polodarb/GMS-Flags/assets/69535896/453fc651-5145-4401-9217-3ca5d4847b80)

**Comment by polodarb** [comment]
Can you record a log and send it to gmsflags@gmail.com?

**Comment by Rafee-M** [comment]
How do I record a log?

**Comment by polodarb** [comment]
Using MatLog or LogFox, for example

**Comment by EGirlEnthusiast** [comment]
I have the same issue. For me I'm using micro g and no google services. Perhaps this app depends on them? Seeing some errors in LogFox related to micro g. Can you confirmbylu are also using micro g, Rafee-M?

**Comment by Rafee-M** [comment]
My bad, forgot to send the log file. But yes I have removed gms and am using microg at the moment

**Comment by transaero21** [comment]
I don't think microG manages or even creates the phenotype database. Сlosing for now. You can reopen the issue if I'm wrong.

**Comment by Rafee-M** [comment]
I've sent the relevant logs to gmsflags@gmail.com. As this issue seems to be occuring on more than one device I feel like it's a bug connected to the absence of GMS

**Comment by polodarb** [comment]
Thanks, @Rafee-M! I looked at the log and I think it's impossible to get this to work on MicroG and others like it

**Comment by selfmusing** [comment]
> Thanks, @Rafee-M! I looked at the log and I think it's impossible to get this to work on MicroG and others like it

I have the same issue on A15 aosp ( Gapps build )

Using Kernel SU
