### ISSUE TITLE
Flag support for maps auto rotate. 

### ISSUE THREAD

**Issue by Gawd21** [polodarb/GMS-Flags#39]
The newest version of the maps will auto rotate no matter what, even with the slightest movement of your phone. Google doesn't see this as an issue, and it makes using their maps useless for me. So I'm wondering if you could add a flag to turn this off when not connected to any device, or if you know which flag it is, as most are just numbers. 
Thank You.

**Comment by polodarb** [comment]
Hello, unfortunately at the moment there is no way to change the flags of the google maps
